name: github_flutter
description: A Flutter Version of GitHub Client.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # https://github.com/flutter/cupertino_icons
  cupertino_icons: ^0.1.2
  # https://github.com/brianegan/font_awesome_flutter
  font_awesome_flutter: ^8.4.0
  # https://github.com/PonnamKarthik/FlutterToast
  fluttertoast: ^3.1.3
  # https://github.com/ReactiveX/rxdart
  rxdart: ^0.23.1
  # https://github.com/flutterchina/dio
  dio: ^3.0.7
  # https://github.com/flutter/plugins/tree/master/packages/connectivity
  connectivity: ^0.4.6+1
  # https://pub.flutter-io.cn/packages/shared_preferences#-readme-tab-
  shared_preferences: ^0.5.6
  # https://github.com/rrousselGit/provider
  provider: ^4.0.1
  # https://github.com/brianegan/flutter_redux
  flutter_redux: ^0.6.0
  # https://github.com/xuelongqy/flutter_easyrefresh
  flutter_easyrefresh: ^2.0.8
  # https://github.com/flutter/plugins/tree/master/packages/path_provider
  path_provider: ^1.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
